Updating pbash_utils

diff --git a/pinstall/pinstall b/pinstall/pinstall
--- a/pinstall/pinstall
+++ b/pinstall/pinstall
@@ -1,5 +1,29 @@
 #!/usr/bin/env bash
 
+getopt_args=( -o "q" -l "quiet" -- "$@" )
+getopt "${getopt_args[@]}" > /dev/null || exit $?
+PARSED_OPTIONS=$(getopt "${getopt_args[@]}")
+eval set -- "${PARSED_OPTIONS[@]}"
+
+quiet="false"
+
+while true; do
+  case "$1" in
+    -q|--quiet)
+      quiet="true"
+      shift
+      ;;
+    --)
+      shift
+      break
+      ;;
+    *)
+      echo "Unexpected option: $1" >&2
+      exit 1
+      ;;
+  esac
+done
+
 installation_path="$HOME/.local/bin/"
 [ -d $HOME/.local/bin ] || mkdir -p $HOME/.local/bin
 
@@ -15,6 +39,10 @@ for p in "$@"
 do
   p="$(realpath "$p")"
   bn="$(basename "$p")"
-  [ -f "$p" ] && echo "Installing: $bn" && cp "$p" "${installation_path}${bn}" && chmod +x "${installation_path}${bn}" || { echo "Installation failed"; exit 1; }
+  if [ -f "$p" ]
+  then
+    [ "$quiet" == "true" ] || echo "Installing: $bn"
+    cp "$p" "${installation_path}${bn}" && chmod +x "${installation_path}${bn}" || { echo "Installation failed"; exit 1; }
+  fi
   sed -i "${sed_args[@]}" "${installation_path}${bn}"
 done
