Merging from main (#6)
* Updating pinstall

* Source script fixes

* Fixes in aliases

* Fixes in aliases

* Update install_alias

* Adding _complete.sh for pinstall

* Create update-pbash-utils

* Update update-pbash-utils

* Update update-pbash-utils

* Update update-pbash-utils

* Added pbash-args.sh

* Added pbash-args.sh

* Added pbash-args.sh and used pflags in some scripts

* Update README.md

* Update pbu_init.sh

* Create ssh-exit

* Update _complete.sh

* Delete pssh/pssh

* Update peval

* Update pbu_init.sh

* Update pinstall

* Update pinstall

* Update pinstall

* Update pinstall

* Update pbu_init.sh

* Added vars.envs file

* Update vars.envs

* Update copy-to-clipboard

* Update copy-to-clipboard

* Update copy-to-clipboard

* Create less-which

* Create vim-which

* pflags fixes

* Create rsync-to-remote

* Making name as optional in pinstall

* Updated command names

* Moved command name under parse subcommand

* Refactoring

* Updated vars with pflags

* Update update-pbash-utils

* Update rsync-to-remote

diff --git a/pinstall/pinstall b/pinstall/pinstall
--- a/pinstall/pinstall
+++ b/pinstall/pinstall
@@ -1,5 +1,32 @@
 #!/usr/bin/env bash
 
+function error_echo() {
+  echo -e "\e[01;31m${@}\e[0m"
+}
+
+name=()
+content=()
+file=()
+
+parsed=$(pflags parse --name "$(basename "$0")" \
+  ---- -l name -t string --default '' --help "Name of the installation" \
+    -- -l content -t string --default '' --help "Content needs to be written to the installed file" \
+    -- -l file -t string --default '' --help "Path of file being installed" \
+    -- -l quiet -t bool --help "Stop printing installation logs" \
+  ---- "$@") || exit $?
+pflags printhelp $parsed && exit
+
+name=$(pflags get -n name "$parsed" ) || exit $?
+content=$(pflags get -n content "$parsed" ) || exit $?
+file=$(pflags get -n file "$parsed" ) || exit $?
+quiet=$(pflags get -n quiet "$parsed" ) || exit $?
+
+[ "$name" == "" ] && [ "$content" == "" ] && [ "$file" == "" ] && { error_echo "No argument provided."; exit 1; }
+[ ! "$content" == "" ] && [ ! "$file" == "" ] && { error_echo "Only one of --content or --file is expected."; exit 1; }
+[ ! "$content" == "" ] && [ "$name" == "" ] && { error_echo "--name is required argument along with --content."; exit 1; }
+
+[ "$name" == "" ] && name="$(basename "$(realpath "$file")")"
+
 installation_path="$HOME/.local/bin/"
 [ -d $HOME/.local/bin ] || mkdir -p $HOME/.local/bin
 
@@ -11,14 +38,19 @@ sed_args=()
 [[ "$OSTYPE" == "darwin"* ]] && sed_args+=( "" )
 sed_args+=( "s/$default_bash/$evaluated_bash/1" )
 
-for p in "$@"
-do
-  p="$(realpath "$p")"
-  bn="$(basename "$p")"
-  if [ -f "$p" ]
-  then
-    [ "$quiet" == "true" ] || echo "Installing: $bn"
-    cp "$p" "${installation_path}${bn}" && chmod +x "${installation_path}${bn}" || { echo "Installation failed"; exit 1; }
-  fi
-  sed -i "${sed_args[@]}" "${installation_path}${bn}"
-done
+rp=""
+if [ ! "$content" == "" ]
+then
+  rp="/tmp/$name"
+  printf "$content" > "$rp"
+else
+  rp="$(realpath "$file")"
+fi
+
+wp="${installation_path}${name}"
+
+[ -f "$rp" ] || { echo "Installation failed, $rp file do not exist"; exit 1; }
+
+[ "$quiet" == "true" ] || echo "Installing: $name"
+cp "$rp" "$wp" && chmod +x "$wp" || { echo "Installation failed"; exit 1; }
+sed -i "${sed_args[@]}" "$wp"
diff --git a/pinstall/puninstall b/pinstall/puninstall
--- a/pinstall/puninstall
+++ b/pinstall/puninstall
@@ -1,9 +1,17 @@
 #!/usr/bin/env bash
 
-installation_path="$HOME/.local/bin/"
-[ -d $HOME/.local/bin ] || { echo "Uninstallation failed"; exit 1; }
+function error_echo() {
+  echo -e "\e[01;31m${@}\e[0m"
+}
 
-for f in "$@"
-do
-  [ -f "${installation_path}${f}" ] && echo "Uninstalling: $f" && rm "${installation_path}${f}" || { echo "Uninstallation failed"; exit 1; }
-done
+parsed=$(pflags parse --name "$0" ---- -l name -t string -r -h "Name of command" ---- "$@") || exit
+pflags printhelp "$parsed" && exit
+
+name="$(pflags get --name name "$parsed")" || exit
+
+installation_path="$HOME/.local/bin/"
+[ -d $HOME/.local/bin ] || { error_echo "Uninstallation failed"; exit 1; }
+
+p="${installation_path}${name}"
+
+[ -f "$p" ] && echo "Uninstalling: $name" && rm "$p" || { error_echo "$p: Uninstallation failed"; exit 1; }
