Updating pinstall

diff --git a/pinstall/puninstall b/pinstall/puninstall
--- a/pinstall/puninstall
+++ b/pinstall/puninstall
@@ -1,9 +1,18 @@
 #!/usr/bin/env bash
 
-installation_path="$HOME/.local/bin/"
-[ -d $HOME/.local/bin ] || { echo "Uninstallation failed"; exit 1; }
+function error_echo() {
+  echo -e "\e[01;31m${@}\e[0m"
+}
 
-for f in "$@"
-do
-  [ -f "${installation_path}${f}" ] && echo "Uninstalling: $f" && rm "${installation_path}${f}" || { echo "Uninstallation failed"; exit 1; }
-done
+source pbash-args.sh || { echo "pbash-args.sh is not installed"; exit 1; }
+
+pbash.args.extract -l name: -o name -- "$@"
+
+[ "$name" == "" ] && { error_echo "--name is required argument."; exit 1; }
+
+installation_path="$HOME/.local/bin/"
+[ -d $HOME/.local/bin ] || { error_echo "Uninstallation failed"; exit 1; }
+
+p="${installation_path}${name}"
+
+[ -f "$p" ] && echo "Uninstalling: $name" && rm "$p" || { error_echo "Uninstallation failed"; exit 1; }
